name: Run Postman Collection

on:
  push:
    branches:
      - main

jobs:
  run-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install newman
        run: npm install -g newman

      - name: Run collection
        run: newman run APITesting.postman_collection_last.json -e PROD.postman_environment.json -r cli,json --reporter-json-export newman-results.json

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: newman-results
          path: newman-results.json

